---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cov-clear:manifests-applier
  labels:
    app: cov-clear
rules:
  - apiGroups: [""]
    resources: ["namespaces", "services", "serviceaccounts"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "update", "patch"]
