---

# You need to edit the configmap/aws-auth in kube-system to
# assign this role to a role/user in AWS, adding the following block:
#
# mapUsers: |
#  - userarn: arn:aws:iam::12345566:user/github
#    username: cov-clear:github
#    groups:
#      - cov-clear:manifests-applier
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cov-clear:manifests-applier
  namespace: [[env]]
  labels:
    app: cov-clear
    env: [[env]]
roleRef:
  kind: ClusterRole
  name: cov-clear:manifests-applier
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: cov-clear:manifests-applier
    apiGroup: rbac.authorization.k8s.io
