---

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-10-privileged
  labels:
    app: psp-10-privileged
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - NET_BIND_SERVICE
  hostIPC: true
  hostNetwork: true
  hostPID: true
  privileged: true
  fsGroup:
    rule: RunAsAny
  hostPorts:
    - min: 0
      max: 65535
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: covclear:podsecuritypolicy:privileged
  labels:
    app: psp-10-privileged
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - psp-10-privileged
    verbs:
      - use

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: covclear:podsecuritypolicy:privileged
  namespace: kube-system
  labels:
    app: psp-10-privileged
roleRef:
  kind: ClusterRole
  name: covclear:podsecuritypolicy:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
    namespace: kube-system

---

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-99-default
  labels:
    app: psp-99-default
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
spec:
  allowPrivilegeEscalation: false
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  requiredDropCapabilities:
    - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: covclear:podsecuritypolicy:default
  labels:
    app: psp-99-default
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - psp-99-default
    verbs:
      - use

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: covclear:podsecuritypolicy:default
  labels:
    app: psp-99-default
roleRef:
  kind: ClusterRole
  name: covclear:podsecuritypolicy:default
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
