---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-ingress-controller
  namespace: kube-ingress
  labels:
    app: alb-ingress-controller
spec:
  selector:
    matchLabels:
      name: alb-ingress-controller
  template:
    metadata:
      labels:
        name: alb-ingress-controller
    spec:
      containers:
        - name: alb-ingress-controller
          image: docker.io/amazon/aws-alb-ingress-controller:v1.1.7
          args:
            - --ingress-class=alb
            - --cluster-name=[[cluster_name]]
            - --aws-vpc-id=[[vpc_id]]
            - --aws-region=[[vpc_region]]
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 1024Mi
